name: publish

on:
  release:
    types: ["released","prereleased"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-actions
    strategy:
        max-parallel: 1
    steps:
       - name: Download the pack files
         uses: robinraju/release-downloader@v1.10
         id: download-files
         with:
           fileName: "*.zip"
           latest: true
           preRelease: true
           tarBall: false
           zipBall: false

       - name: Publish to Modrinth and CurseForge
         uses: Kir-Antipov/mc-publish@v3.3
         with:
           name: ${{ steps.download-files.outputs.release_name }}
           files: '*.zip'
           loaders: minecraft
           game-versions: "[1.18.2,1.20.4]"
           version-type: alpha

           modrinth-id: iDq9j9UQ
           modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
